### PR TITLE
Add --log-file CLI flag

### LINKED ISSUE #86: Add log file support (and improve log format)
Add some option to create a log file. The log level should probably be either *verbose* or *debug*.

There is also the need for some better logging output format. The current design is cumbersome, takes two lines per message, etc. There's way more elegant examples out in the world, which we could take some inspiration from.

### PR DESCRIPTION
**Pull request by M4eqP**
Closes #86.

This PR introduces a `--log-file` flag. All logs created by this application are stored in this file.

As of yet, the logs are stored in XML format. That's Java's default. It'd satisfy the acceptance criteria, but is most useful for machine processing. The sprint backlog item doesn't define whether this is what was intended. Given the purpose of the tool (running on a CI system to apply changes to infrastructure), it might actually be an advantage to have XML style logs.

Here's an example message:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2020-06-23T23:47:08.956185Z</date>
  <millis>1592956028956</millis>
  <nanos>185000</nanos>
  <sequence>0</sequence>
  <logger>cfctl</logger>
  <level>FINER</level>
  <class>cloud.foundry.cli.crosscutting.logging.Log</class>
  <method>log</method>
  <thread>1</thread>
  <message>enabling debug logging</message>
</record>
[...]
```

It is possible to change the output format if needed. The XML contains a lot of misleading information (e.g., `class` and `method` are clearly wrong) anyway.

### CODE REVIEW

**Comment by M4eqP** [comment]
I already test whether custom handlers work through the unit tests. But I'll look into how to call a PicoCLI command from a unit test, maybe it's doable easily.

What about the log format?

**Comment by M4eqP** [comment]
After lots of fiddling with JUnit, the JVM and PicoCLI I managed to write a test case. The annoying bit is that the way @felix-oq suggested it, we basically have to wait for the network calls to fail, which really increase the runtime of the tests.

The only good part might be that it'll increase the line test coverage, as I had to hook into the `BaseController`. The concept might work for more integration tests. Everyone's welcome to refactor out my work so it's usable in other tests, too.

I'm finishing the unit test (there's a few XML file format annoyances that make Java's `DocumentBuilder` complain), and will push ASAP.

**Comment by felix-oq** [comment]
We should not forget to update the Readme!

**Comment by M4eqP** [comment]
@alexanderKoltman you're absolutely right! Thanks for the hint!

**Pull request merged**
